### ISSUE TITLE
Specify variable node background colour and the border colour

### ISSUE THREAD

**Issue by martinjhnhadley** [DataKnowledge/visNetwork#51]
I would like to be able to vary the background colour of the nodes in my graph but use a border colour to ensure nicely delimitated nodes compared to edges.

I thought that the following should work, but it does not:

```r
nodes <- data.frame(id = 1:3,
                    color = c("lightblue","red","blue"))
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges) %>% visNodes(color = list(border = "black"))
```

![image](https://cloud.githubusercontent.com/assets/9363263/12882053/ac50d8c4-ce46-11e5-8118-3d3894e4af69.png)

I tried providing a vector of colors directly to `visNodes` without success, indeed the colors are retained from the `data.frame` column `color`

```r
visNetwork(nodes, edges) %>% visNodes(color = list(background = c("yellow","pink","blue"), 
border = "black"))
```

![image](https://cloud.githubusercontent.com/assets/9363263/12882089/0a92d360-ce47-11e5-9ddd-5efdcf019bc5.png)

visNetwork is a great package but is under queried on SE, I ask this question here in the Issues rather than SE because of that. I would like to take your feedback from here and post a self-answered question on SE to guide people there, if ok with you.

**Comment by bthieurmel** [comment]
Hi,

This case is interesting. First, we can pass individual options to nodes/edges data.frame, and global option for all nodes / edges with ``visNodes`` and ``visEdges``.

So you can't do that : 

````
visNetwork(nodes, edges) %>% visNodes(color = list(background = c("yellow","pink","blue"), 
border = "black"))
````
But just assign one background and border color with this way : 
````
visNetwork(nodes, edges) %>% visNodes(color = list(background = "blue", 
border = "black"))
````

``color`` can be a simple option with one value, or have a more complex definition. In your first example, it seems that the definition of ``color`` in data.frame overwrite the ``visNodes`` options.

Since 0.2.1, you can now pass complex options (list) directly in data.frame like this : 

````
nodes <- data.frame(id = 1:3,
                    color.background = c("lightblue","red","blue"),
                    color.border = "black")
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges)
````

and so : 

````
nodes <- data.frame(id = 1:3,
                    color.background = c("lightblue","red","blue"))
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges) %>% visNodes(color = list(border = "black"))
````

What is SE ?

**Comment by martinjhnhadley** [comment]
Makes sense! I'll specify the `color.background` and `color.border` in the `node` `data.frame` directly from now on, thanks.

SE == StackExchange, sorry for unnecessary abbreviations
